### ISSUE TITLE
Invite pls

### ISSUE THREAD

**Issue by trnc-ck** [Saleor-Multi-Vendor/saleor-multi-vendor#1]
As I’m really interested and need this feature till autumn. 😉

**Comment by fastengineer** [comment]
Finally someone came, this is good news.
I sent your invitation. Welcome.
We can start sharing tasks. Can you share how much time you can work for this plugin and your expertise, programming languages, back-end, frond-end experience?

**Comment by clemenskroell** [comment]
I created a Gitter channel. Let’s discuss there!

https://gitter.im/Saleor-Multi-Vendor/community
