### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by joelbudu** [Saleor-Multi-Vendor/saleor-multi-vendor#2]
Hello @fastengineer. I'm really interested in this plugin. I know Ruby on Rails and python (non-expert) so may be able to contribute to this if I can. Can we connect?

**Comment by gpillemer** [comment]
Hi, I’m also interested in helping out on this. 
Also agree that this would be a great addition to saleor
I am working on project with a team (much more knowledgeable than me) and the project requires this functionality.
Please let me know when you want to connect and I will reach out to my team too

**Comment by backtrack-5** [comment]
Hi, I am using Saleor. At the moment i am mapping product to vendor using metaclass. I know this is not a good idea. 

I am interested working on this. Please let me know when you want to connect.

Thanks,

**Comment by gpillemer** [comment]
Hi, I am using add_to_class to add vendor foreign key to product model
Would be good to chat about how others are thinking about this

**Comment by mehmetaydogduu** [comment]
Hi guys. I sent invitations to you. Please check your e-mails.
We have a gitter channel. Let's talk on [live chat](https://gitter.im/Saleor-Multi-Vendor/community).

**Comment by joelbudu** [comment]
Whats the link to the bitter channel?

**Comment by binnyFriedman** [comment]
Hi I'm also interested in working on this

**Comment by mehmetaydogduu** [comment]
https://gitter.im/Saleor-Multi-Vendor/community
