### ISSUE TITLE
invite

### ISSUE THREAD

**Issue by RubensRainelli** [Saleor-Multi-Vendor/saleor-multi-vendor#3]
Please let me join
In case we can discuss on Telegram, same username

**Comment by mehmetaydogduu** [comment]
Hi, we have gitter.im channel

**Comment by Beardless-sheik** [comment]
Hey. Still working on this?

**Comment by mehmetaydogduu** [comment]
We are active on gitter.

**Comment by barziv5** [comment]
Would be happy to donate for a developer to do this

**Comment by mehmetaydogduu** [comment]
@barziv5 Maybe we can make Kickstarter campaign.
