### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by barziv5** [Saleor-Multi-Vendor/saleor-multi-vendor#5]
Hi was wondering, if spree is good why not use it's marketplace feature?

Why is saleor better than spree? Thanks

**Comment by mehmetaydogduu** [comment]
It is quite good but there is some problems related to business:
- It is developed with ruby and it is very hard to hire a ruby developer
- Admin panel ui is very old (Store UI is new and looking good. Maybe they can renew the admin ui)
- Lack of graphQL and hard to develop GraphQL apis with ruby.
